// --- SUGESTÕES PRONTAS (CATÁLOGO) ---
// --- SUGESTÕES PRONTAS (CATÁLOGO EXPANDIDO) ---
// --- SUGESTÕES PRONTAS (200 ITENS - CATÁLOGO COMPLETO) ---
// --- SUGESTÕES PRONTAS (CORRIGIDAS PARA PADRÃO RPG) ---
export const MISSIONS_CATALOG = [
    // --- 🌅 ROTINA MATINAL (1-15) ---
    { id: 'sys_1', title: 'Arrumar a Cama', icon: 'bed', reward: 50, difficulty: 'common', description: 'Lençol esticado e travesseiro no lugar.', is_system: true, is_recurring: true, recurrence_days: [0,1,2,3,4,5,6] },
    { id: 'sys_2', title: 'Escovar os Dentes (Manhã)', icon: 'toothbrush', reward: 20, difficulty: 'common', description: 'Hálito fresco para começar o dia.', is_system: true, is_recurring: true, recurrence_days: [0,1,2,3,4,5,6] },
    { id: 'sys_3', title: 'Lavar o Rosto', icon: 'face-man-shimmer', reward: 15, difficulty: 'common', description: 'Acordar de verdade!', is_system: true },
    { id: 'sys_4', title: 'Tirar o Pijama', icon: 'tshirt-crew', reward: 15, difficulty: 'common', description: 'Colocar roupa do dia ou uniforme.', is_system: true },
    { id: 'sys_5', title: 'Guardar o Pijama', icon: 'archive', reward: 20, difficulty: 'common', description: 'Dobrado ou embaixo do travesseiro.', is_system: true },
    { id: 'sys_6', title: 'Pentear o Cabelo', icon: 'hair-dryer', reward: 15, difficulty: 'common', description: 'Cabelo arrumado sem nós.', is_system: true },
    { id: 'sys_7', title: 'Tomar Café da Manhã', icon: 'coffee', reward: 30, difficulty: 'common', description: 'Comer tudo para ter energia.', is_system: true },
    { id: 'sys_8', title: 'Levar Prato pra Pia', icon: 'silverware', reward: 20, difficulty: 'common', description: 'Não deixar na mesa após comer.', is_system: true },
    { id: 'sys_9', title: 'Arrumar a Mochila', icon: 'bag-personal', reward: 40, difficulty: 'rare', description: 'Conferir cadernos e estojo.', is_system: true },
    { id: 'sys_10', title: 'Passar Protetor Solar', icon: 'weather-sunny', reward: 20, difficulty: 'common', description: 'Proteger a pele antes de sair.', is_system: true },
    { id: 'sys_11', title: 'Calçar Sapatos', icon: 'shoe-sneaker', reward: 15, difficulty: 'common', description: 'E amarrar o cadarço se tiver.', is_system: true },
    { id: 'sys_12', title: 'Encher Garrafa d\'Água', icon: 'bottle-soda', reward: 20, difficulty: 'common', description: 'Levar água para a escola.', is_system: true },
    { id: 'sys_13', title: 'Dar Tchau pra Família', icon: 'hand-wave', reward: 10, difficulty: 'common', description: 'Sair de casa com alegria.', is_system: true },
    { id: 'sys_14', title: 'Tomar Vitaminas', icon: 'pill', reward: 20, difficulty: 'common', description: 'Cuidar da saúde.', is_system: true },
    { id: 'sys_15', title: 'Acordar no Horário', icon: 'alarm', reward: 50, difficulty: 'rare', description: 'Levantar sem enrolar na cama.', is_system: true },

    // --- 🌙 ROTINA NOTURNA (16-30) ---
    { id: 'sys_16', title: 'Tomar Banho', icon: 'shower', reward: 40, difficulty: 'common', description: 'Banho completo, lavar bem o pé!', is_system: true },
    { id: 'sys_17', title: 'Escovar os Dentes (Noite)', icon: 'toothbrush', reward: 30, difficulty: 'common', description: 'Xô cáries antes de dormir.', is_system: true },
    { id: 'sys_18', title: 'Passar Fio Dental', icon: 'tooth', reward: 40, difficulty: 'rare', description: 'Limpeza completa dos dentes.', is_system: true },
    { id: 'sys_19', title: 'Colocar Roupa Suja no Cesto', icon: 'basket', reward: 20, difficulty: 'common', description: 'Nada de roupa no chão do banheiro.', is_system: true },
    { id: 'sys_20', title: 'Pendurar a Toalha', icon: 'hanger', reward: 25, difficulty: 'common', description: 'Deixar esticada para secar.', is_system: true },
    { id: 'sys_21', title: 'Separar Uniforme', icon: 'tshirt-crew-outline', reward: 40, difficulty: 'rare', description: 'Deixar tudo pronto para manhã.', is_system: true },
    { id: 'sys_22', title: 'Ler 10 min antes de dormir', icon: 'book-open-variant', reward: 60, difficulty: 'rare', description: 'Relaxar a mente.', is_system: true },
    { id: 'sys_23', title: 'Ir pra Cama no Horário', icon: 'bed-clock', reward: 80, difficulty: 'epic', description: 'Sem reclamar e sem telas.', is_system: true },
    { id: 'sys_24', title: 'Apagar as Luzes', icon: 'lightbulb-off', reward: 10, difficulty: 'common', description: 'Economizar energia.', is_system: true },
    { id: 'sys_25', title: 'Fazer Xixi antes de dormir', icon: 'toilet', reward: 10, difficulty: 'common', description: 'Evitar acordar de madrugada.', is_system: true },
    { id: 'sys_26', title: 'Guardar Eletrônicos', icon: 'cellphone-off', reward: 50, difficulty: 'rare', description: 'Celular longe da cama.', is_system: true },
    { id: 'sys_27', title: 'Agradecer pelo Dia', icon: 'hands-pray', reward: 20, difficulty: 'common', description: 'Momento de gratidão.', is_system: true },
    { id: 'sys_28', title: 'Preparar Lancheira', icon: 'food-apple', reward: 50, difficulty: 'rare', description: 'Deixar o lanche pronto.', is_system: true },
    { id: 'sys_29', title: 'Carregar o Celular', icon: 'battery-charging', reward: 15, difficulty: 'common', description: 'Colocar na tomada na sala.', is_system: true },
    { id: 'sys_30', title: 'Beber Água', icon: 'cup-water', reward: 10, difficulty: 'common', description: 'Último gole do dia.', is_system: true },

    // --- 🧹 TAREFAS DE CASA: QUARTO (31-45) ---
    { id: 'sys_31', title: 'Guardar Brinquedos', icon: 'toy-brick', reward: 60, difficulty: 'rare', description: 'Chão livre de perigos.', is_system: true },
    { id: 'sys_32', title: 'Organizar a Escrivaninha', icon: 'desk', reward: 50, difficulty: 'rare', description: 'Mesa limpa para estudar.', is_system: true },
    { id: 'sys_33', title: 'Organizar Sapatos', icon: 'shoe-formal', reward: 40, difficulty: 'common', description: 'Pares juntos no armário.', is_system: true },
    { id: 'sys_34', title: 'Dobrar Pijamas', icon: 'tshirt-v', reward: 30, difficulty: 'common', description: 'Não deixar embolado.', is_system: true },
    { id: 'sys_35', title: 'Limpar Embaixo da Cama', icon: 'ghost', reward: 80, difficulty: 'epic', description: 'Caça aos monstros de poeira.', is_system: true },
    { id: 'sys_36', title: 'Tirar o Pó dos Móveis', icon: 'feather', reward: 60, difficulty: 'rare', description: 'Passar pano nas prateleiras.', is_system: true },
    { id: 'sys_37', title: 'Abrir a Janela', icon: 'window-open', reward: 20, difficulty: 'common', description: 'Arejar o quarto.', is_system: true },
    { id: 'sys_38', title: 'Fechar a Janela', icon: 'window-closed', reward: 20, difficulty: 'common', description: 'Antes de escurecer.', is_system: true },
    { id: 'sys_39', title: 'Trocar Fronha', icon: 'bed-double', reward: 50, difficulty: 'rare', description: 'Colocar fronha limpa.', is_system: true },
    { id: 'sys_40', title: 'Organizar Gaveta', icon: 'archive', reward: 100, difficulty: 'epic', description: 'Arrumar gaveta de camisetas.', is_system: true },
    { id: 'sys_41', title: 'Esvaziar Lixeira do Quarto', icon: 'trash-can-outline', reward: 40, difficulty: 'common', description: 'Jogar papel fora.', is_system: true },
    { id: 'sys_42', title: 'Guardar Livros', icon: 'book', reward: 40, difficulty: 'common', description: 'Livros na estante.', is_system: true },
    { id: 'sys_43', title: 'Passar Aspirador no Quarto', icon: 'robot-vacuum', reward: 120, difficulty: 'epic', description: 'Carpete limpinho.', is_system: true },
    { id: 'sys_44', title: 'Organizar Coleção', icon: 'cards', reward: 50, difficulty: 'rare', description: 'Arrumar cards, carrinhos ou bonecas.', is_system: true },
    { id: 'sys_45', title: 'Faxina Geral no Quarto', icon: 'star-four-points', reward: 300, difficulty: 'legendary', description: 'Deixar o quarto brilhando!', is_system: true, use_critical: true, critical_type: 'bonus_coins', critical_chance: 50 },

    // --- 🍽️ TAREFAS DE CASA: COZINHA (46-65) ---
    { id: 'sys_46', title: 'Colocar a Mesa', icon: 'table-furniture', reward: 40, difficulty: 'common', description: 'Pratos, copos e talheres.', is_system: true },
    { id: 'sys_47', title: 'Tirar a Mesa', icon: 'table-off', reward: 40, difficulty: 'common', description: 'Levar tudo para a pia.', is_system: true },
    { id: 'sys_48', title: 'Lavar a Louça (Pouca)', icon: 'cup', reward: 80, difficulty: 'rare', description: 'Lavar copos e pratos do lanche.', is_system: true },
    { id: 'sys_49', title: 'Lavar a Louça (Muita)', icon: 'silverware-clean', reward: 200, difficulty: 'epic', description: 'Lavar panelas e pratos do almoço.', is_system: true, use_critical: true, critical_type: 'bonus_coins', critical_chance: 30 },
    { id: 'sys_50', title: 'Secar a Louça', icon: 'paper-roll', reward: 60, difficulty: 'rare', description: 'Secar tudo com pano de prato.', is_system: true },
    { id: 'sys_51', title: 'Guardar a Louça', icon: 'cupboard', reward: 70, difficulty: 'rare', description: 'Colocar nos armários certos.', is_system: true },
    { id: 'sys_52', title: 'Encher Garrafas', icon: 'bottle-soda-classic', reward: 30, difficulty: 'common', description: 'Água gelada na geladeira.', is_system: true },
    { id: 'sys_53', title: 'Limpar a Mesa', icon: 'spray', reward: 40, difficulty: 'common', description: 'Passar pano após refeição.', is_system: true },
    { id: 'sys_54', title: 'Varrer a Cozinha', icon: 'broom', reward: 60, difficulty: 'rare', description: 'Tirar migalhas do chão.', is_system: true },
    { id: 'sys_55', title: 'Ajudar a Cozinhar', icon: 'chef-hat', reward: 100, difficulty: 'rare', description: 'Ser o assistente do chef.', is_system: true },
    { id: 'sys_56', title: 'Guardar Compras', icon: 'cart-arrow-down', reward: 80, difficulty: 'rare', description: 'Ajudar a guardar itens do mercado.', is_system: true },
    { id: 'sys_57', title: 'Fazer um Suco', icon: 'blender', reward: 50, difficulty: 'rare', description: 'Preparar suco natural.', is_system: true },
    { id: 'sys_58', title: 'Organizar Potes', icon: 'package-variant', reward: 60, difficulty: 'rare', description: 'Achar as tampas dos potes.', is_system: true },
    { id: 'sys_59', title: 'Limpar Micro-ondas', icon: 'microwave', reward: 90, difficulty: 'epic', description: 'Tirar respingos de comida.', is_system: true },
    { id: 'sys_60', title: 'Trocar o Lixo da Pia', icon: 'delete-empty', reward: 30, difficulty: 'common', description: 'Esvaziar a lixeirinha.', is_system: true },
    { id: 'sys_61', title: 'Fazer o Próprio Lanche', icon: 'bread-slice', reward: 50, difficulty: 'rare', description: 'Preparar sanduíche ou cereal.', is_system: true },
    { id: 'sys_62', title: 'Alimentar Fermento', icon: 'bacteria', reward: 40, difficulty: 'rare', description: 'Para famílias que cultivam.', is_system: true },
    { id: 'sys_63', title: 'Pegar Água para os Pais', icon: 'glass-cocktail', reward: 20, difficulty: 'common', description: 'Gentileza na cozinha.', is_system: true },
    { id: 'sys_64', title: 'Organizar Geladeira', icon: 'fridge', reward: 150, difficulty: 'epic', description: 'Jogar fora vencidos e organizar.', is_system: true },
    { id: 'sys_65', title: 'Fazer Café (com supervisão)', icon: 'coffee-maker', reward: 60, difficulty: 'rare', description: 'Preparar o café da tarde.', is_system: true },

    // --- 🚽 BANHEIRO & LAVANDERIA (66-80) ---
    { id: 'sys_66', title: 'Trocar Rolo de Papel', icon: 'paper-roll', reward: 20, difficulty: 'common', description: 'Não deixar acabar!', is_system: true },
    { id: 'sys_67', title: 'Limpar Espelho', icon: 'spray', reward: 60, difficulty: 'rare', description: 'Tirar marcas de dente.', is_system: true },
    { id: 'sys_68', title: 'Recolher Lixo do Banheiro', icon: 'trash-can', reward: 50, difficulty: 'rare', description: 'Esvaziar lixeira.', is_system: true },
    { id: 'sys_69', title: 'Separar Roupa Colorida', icon: 'palette-swatch', reward: 80, difficulty: 'epic', description: 'Separar branca de colorida.', is_system: true },
    { id: 'sys_70', title: 'Colocar Roupa na Máquina', icon: 'washing-machine', reward: 100, difficulty: 'rare', description: 'Ajudar a lavar roupa.', is_system: true },
    { id: 'sys_71', title: 'Estender Roupas', icon: 'hanger', reward: 120, difficulty: 'epic', description: 'Pendurar no varal.', is_system: true },
    { id: 'sys_72', title: 'Recolher Roupas Secas', icon: 'basket', reward: 80, difficulty: 'rare', description: 'Trazer do varal.', is_system: true },
    { id: 'sys_73', title: 'Dobrar Meias', icon: 'shoe-print', reward: 50, difficulty: 'rare', description: 'Encontrar os pares.', is_system: true },
    { id: 'sys_74', title: 'Dobrar Camisetas', icon: 'tshirt-v-outline', reward: 80, difficulty: 'rare', description: 'Deixar bem dobradinho.', is_system: true },
    { id: 'sys_75', title: 'Guardar Roupas Limpas', icon: 'archive', reward: 70, difficulty: 'rare', description: 'Nas gavetas certas.', is_system: true },
    { id: 'sys_76', title: 'Limpar a Pia', icon: 'water-pump', reward: 40, difficulty: 'common', description: 'Tirar fios de cabelo e pasta.', is_system: true },
    { id: 'sys_77', title: 'Trocar Toalha de Rosto', icon: 'tshirt-crew', reward: 30, difficulty: 'common', description: 'Colocar uma limpa.', is_system: true },
    { id: 'sys_78', title: 'Bater Tapete do Banheiro', icon: 'rug', reward: 40, difficulty: 'common', description: 'Tirar a poeira.', is_system: true },
    { id: 'sys_79', title: 'Organizar Produtos', icon: 'shaker', reward: 50, difficulty: 'rare', description: 'Shampoo e sabonete no lugar.', is_system: true },
    { id: 'sys_80', title: 'Ajudar a Lavar Banheiro', icon: 'brush', reward: 300, difficulty: 'legendary', description: 'Tarefa pesada com supervisão.', is_system: true, use_critical: true, critical_type: 'custom_item', critical_custom_reward: 'Pizza no Jantar', critical_chance: 25 },

    // --- 📚 ESCOLA & ESTUDO (81-105) ---
    { id: 'sys_81', title: 'Dever de Casa Completo', icon: 'school', reward: 150, difficulty: 'rare', description: 'Lição feita com capricho.', is_system: true },
    { id: 'sys_82', title: 'Estudar para Prova', icon: 'brain', reward: 200, difficulty: 'epic', description: 'Foco total por 30 min.', is_system: true },
    { id: 'sys_83', title: 'Ler 15 Páginas', icon: 'book-open-variant', reward: 100, difficulty: 'rare', description: 'Avançar no livro.', is_system: true },
    { id: 'sys_84', title: 'Aula de Inglês', icon: 'translate', reward: 100, difficulty: 'rare', description: 'Praticar vocabulário.', is_system: true },
    { id: 'sys_85', title: 'Fazer Caligrafia', icon: 'pen', reward: 60, difficulty: 'rare', description: 'Melhorar a letra.', is_system: true },
    { id: 'sys_86', title: 'Treinar Tabuada', icon: 'calculator', reward: 80, difficulty: 'rare', description: 'Matemática afiada.', is_system: true },
    { id: 'sys_87', title: 'Projeto de Ciências', icon: 'flask', reward: 250, difficulty: 'legendary', description: 'Trabalho escolar grande.', is_system: true, use_critical: true, critical_chance: 30, critical_type: 'bonus_coins' },
    { id: 'sys_88', title: 'Apontar Lápis', icon: 'pencil', reward: 30, difficulty: 'common', description: 'Preparar o estojo.', is_system: true },
    { id: 'sys_89', title: 'Organizar Cadernos', icon: 'notebook', reward: 40, difficulty: 'common', description: 'Mochila em ordem.', is_system: true },
    { id: 'sys_90', title: 'Ler em Voz Alta', icon: 'microphone', reward: 70, difficulty: 'rare', description: 'Treinar oratória.', is_system: true },
    { id: 'sys_91', title: 'Fazer Resumo', icon: 'file-document-edit', reward: 120, difficulty: 'epic', description: 'Resumir o que aprendeu.', is_system: true },
    { id: 'sys_92', title: 'Pesquisa Escolar', icon: 'google-chrome', reward: 100, difficulty: 'rare', description: 'Buscar informações.', is_system: true },
    { id: 'sys_93', title: 'Limpar Estojo', icon: 'pencil-box', reward: 50, difficulty: 'common', description: 'Tirar sujeira de apontador.', is_system: true },
    { id: 'sys_94', title: 'Semana de Provas', icon: 'calendar-alert', reward: 500, difficulty: 'legendary', description: 'Sobreviver à semana de provas!', is_system: true, use_critical: true, critical_type: 'custom_item', critical_custom_reward: 'Passeio no Shopping', critical_chance: 100 },
    { id: 'sys_95', title: 'Nota 10 (Máxima)', icon: 'star-circle', reward: 1000, difficulty: 'legendary', description: 'Esforço máximo recompensado.', is_system: true, use_critical: true, critical_type: 'bonus_coins', critical_chance: 100 },
    { id: 'sys_96', title: 'Nota Azul (Média)', icon: 'check-circle', reward: 300, difficulty: 'epic', description: 'Passou de ano/bimestre.', is_system: true },
    { id: 'sys_97', title: 'Aula de Música', icon: 'music-clef-treble', reward: 100, difficulty: 'rare', description: 'Ir para a aula de instrumento.', is_system: true },
    { id: 'sys_98', title: 'Aula de Esporte', icon: 'soccer', reward: 100, difficulty: 'rare', description: 'Ir para o treino.', is_system: true },
    { id: 'sys_99', title: 'Não Atrasar pra Escola', icon: 'run-fast', reward: 50, difficulty: 'rare', description: 'Sair de casa na hora.', is_system: true },
    { id: 'sys_100', title: 'Uniforme Limpo', icon: 'tshirt-crew', reward: 30, difficulty: 'common', description: 'Cuidar do uniforme.', is_system: true },

    // --- 🐕 PETS (101-115) ---
    { id: 'sys_101', title: 'Dar Comida pro Pet', icon: 'bowl', reward: 30, difficulty: 'common', description: 'Encher a tigela.', is_system: true },
    { id: 'sys_102', title: 'Trocar Água do Pet', icon: 'water', reward: 30, difficulty: 'common', description: 'Água fresca sempre.', is_system: true },
    { id: 'sys_103', title: 'Passear com Cachorro', icon: 'dog-service', reward: 150, difficulty: 'epic', description: 'Volta no quarteirão.', is_system: true },
    { id: 'sys_104', title: 'Limpar Caixinha do Gato', icon: 'cat', reward: 100, difficulty: 'rare', description: 'Tirar a sujeira.', is_system: true },
    { id: 'sys_105', title: 'Dar Banho no Pet', icon: 'dog', reward: 250, difficulty: 'legendary', description: 'Deixar o bicho cheiroso.', is_system: true, use_critical: true, critical_type: 'bonus_coins', critical_chance: 30 },
    { id: 'sys_106', title: 'Brincar com o Pet', icon: 'tennis-ball', reward: 50, difficulty: 'common', description: 'Gastar energia dele.', is_system: true },
    { id: 'sys_107', title: 'Escovar Pelo', icon: 'hair-dryer', reward: 60, difficulty: 'rare', description: 'Tirar pelos soltos.', is_system: true },
    { id: 'sys_108', title: 'Limpar Quintal (Caca)', icon: 'emoticon-poop', reward: 120, difficulty: 'epic', description: 'Recolher sujeira do quintal.', is_system: true },
    { id: 'sys_109', title: 'Limpar Gaiola/Aquário', icon: 'fish', reward: 150, difficulty: 'epic', description: 'Hamster, passarinho ou peixe.', is_system: true },
    { id: 'sys_110', title: 'Ensinar Truque', icon: 'school', reward: 100, difficulty: 'epic', description: 'Ensinar a sentar ou dar a pata.', is_system: true },
    { id: 'sys_111', title: 'Verificar Ração', icon: 'sack', reward: 20, difficulty: 'common', description: 'Avisar se estiver acabando.', is_system: true },
    { id: 'sys_112', title: 'Lavar Potes do Pet', icon: 'dishwasher', reward: 50, difficulty: 'rare', description: 'Lavar tigelas com sabão.', is_system: true },
    { id: 'sys_113', title: 'Recolher Brinquedos', icon: 'bone', reward: 30, difficulty: 'common', description: 'Guardar ossinhos.', is_system: true },
    { id: 'sys_114', title: 'Dar Remédio pro Pet', icon: 'pill', reward: 80, difficulty: 'epic', description: 'Se o pet estiver doente.', is_system: true },
    { id: 'sys_115', title: 'Carinho no Pet', icon: 'heart', reward: 10, difficulty: 'common', description: 'Amar o bichinho.', is_system: true },

    // --- 🤝 COMPORTAMENTO & SOCIAL (116-135) ---
    { id: 'sys_116', title: 'Não Brigar com Irmão', icon: 'account-group', reward: 150, difficulty: 'epic', description: 'Dia de paz em casa.', is_system: true },
    { id: 'sys_117', title: 'Dizer Por Favor', icon: 'hand-heart', reward: 50, difficulty: 'common', description: 'Educação máxima hoje.', is_system: true },
    { id: 'sys_118', title: 'Obedecer na Primeira', icon: 'ear-hearing', reward: 100, difficulty: 'epic', description: 'Atender logo que chamado.', is_system: true },
    { id: 'sys_119', title: 'Compartilhar Brinquedo', icon: 'gift-open', reward: 70, difficulty: 'rare', description: 'Ser generoso.', is_system: true },
    { id: 'sys_120', title: 'Não Gritar', icon: 'volume-off', reward: 80, difficulty: 'rare', description: 'Falar baixo dentro de casa.', is_system: true },
    { id: 'sys_121', title: 'Pedir Desculpas', icon: 'message-alert', reward: 60, difficulty: 'rare', description: 'Reconhecer erro.', is_system: true },
    { id: 'sys_122', title: 'Não Falar Palavrão', icon: 'volume-off', reward: 100, difficulty: 'epic', description: 'Linguagem limpa.', is_system: true },
    { id: 'sys_123', title: 'Ajudar Alguém', icon: 'charity', reward: 100, difficulty: 'rare', description: 'Fazer uma gentileza.', is_system: true },
    { id: 'sys_124', title: 'Ligar para os Avós', icon: 'phone', reward: 60, difficulty: 'common', description: 'Dar atenção à família.', is_system: true },
    { id: 'sys_125', title: 'Escrever Carta/Desenho', icon: 'email-edit', reward: 70, difficulty: 'rare', description: 'Para alguém especial.', is_system: true },
    { id: 'sys_126', title: 'Esperar a Vez', icon: 'timer-sand', reward: 50, difficulty: 'rare', description: 'Ter paciência.', is_system: true },
    { id: 'sys_127', title: 'Falar a Verdade', icon: 'shield-check', reward: 100, difficulty: 'epic', description: 'Mesmo quando for difícil.', is_system: true },
    { id: 'sys_128', title: 'Não Reclamar', icon: 'emoticon-happy', reward: 120, difficulty: 'epic', description: 'Dia positivo.', is_system: true },
    { id: 'sys_129', title: 'Cumprimentar Pessoas', icon: 'handshake', reward: 40, difficulty: 'common', description: 'Bom dia/Boa tarde.', is_system: true },
    { id: 'sys_130', title: 'Doar Brinquedo Antigo', icon: 'gift-outline', reward: 300, difficulty: 'legendary', description: 'Generosidade.', is_system: true, use_critical: true, critical_type: 'custom_item', critical_custom_reward: 'Medalha de Ouro', critical_chance: 100 },
    { id: 'sys_131', title: 'Fazer Elogio', icon: 'thumb-up', reward: 30, difficulty: 'common', description: 'Elogiar alguém da casa.', is_system: true },
    { id: 'sys_132', title: 'Respeitar os Mais Velhos', icon: 'account-tie', reward: 50, difficulty: 'rare', description: 'Ouvir com atenção.', is_system: true },
    { id: 'sys_133', title: 'Não Interromper', icon: 'account-voice-off', reward: 60, difficulty: 'rare', description: 'Esperar a pessoa terminar de falar.', is_system: true },
    { id: 'sys_134', title: 'Arrumar Mesa sem Pedir', icon: 'table-star', reward: 150, difficulty: 'epic', description: 'Iniciativa própria.', is_system: true },
    { id: 'sys_135', title: 'Fazer Carinho no Irmão', icon: 'human-child', reward: 50, difficulty: 'common', description: 'Demonstrar afeto.', is_system: true },

    // --- 🥦 SAÚDE & ALIMENTAÇÃO (136-155) ---
    { id: 'sys_136', title: 'Comer Legumes', icon: 'carrot', reward: 60, difficulty: 'rare', description: 'Prato colorido.', is_system: true, use_critical: true, critical_type: 'bonus_coins', critical_chance: 25 },
    { id: 'sys_137', title: 'Comer Fruta', icon: 'food-apple', reward: 40, difficulty: 'common', description: 'Lanche saudável.', is_system: true },
    { id: 'sys_138', title: 'Beber Água', icon: 'cup-water', reward: 20, difficulty: 'common', description: 'Manter hidratação.', is_system: true },
    { id: 'sys_139', title: 'Provar Comida Nova', icon: 'silverware-spoon', reward: 100, difficulty: 'epic', description: 'Experimentar algo diferente.', is_system: true },
    { id: 'sys_140', title: 'Comer Tudo no Prato', icon: 'check-circle-outline', reward: 50, difficulty: 'rare', description: 'Sem desperdício.', is_system: true },
    { id: 'sys_141', title: 'Não Beber Refri', icon: 'bottle-soda-outline', reward: 60, difficulty: 'rare', description: 'Escolher suco ou água.', is_system: true },
    { id: 'sys_142', title: 'Sem Doces Hoje', icon: 'candy-off', reward: 100, difficulty: 'epic', description: 'Dia detox de açúcar.', is_system: true },
    { id: 'sys_143', title: 'Lavar as Mãos', icon: 'hand-water', reward: 15, difficulty: 'common', description: 'Antes de comer.', is_system: true },
    { id: 'sys_144', title: 'Usar Guardanapo', icon: 'paper-roll-outline', reward: 20, difficulty: 'common', description: 'Limpar a boca.', is_system: true },
    { id: 'sys_145', title: 'Mastigar de Boca Fechada', icon: 'face-man', reward: 40, difficulty: 'rare', description: 'Boas maneiras à mesa.', is_system: true },
    { id: 'sys_146', title: 'Tomar Café da Manhã', icon: 'coffee-outline', reward: 30, difficulty: 'common', description: 'Não pular refeição.', is_system: true },
    { id: 'sys_147', title: 'Levar Fruta pra Escola', icon: 'food-apple', reward: 30, difficulty: 'common', description: 'Lancheira saudável.', is_system: true },
    { id: 'sys_148', title: 'Ajudar a Fazer Salada', icon: 'leaf', reward: 50, difficulty: 'rare', description: 'Lavar alface ou tomate.', is_system: true },
    { id: 'sys_149', title: 'Tomar Xarope/Remédio', icon: 'bottle-tonic-plus', reward: 30, difficulty: 'common', description: 'Sem reclamar do gosto.', is_system: true },
    { id: 'sys_150', title: 'Dia Saudável', icon: 'heart-pulse', reward: 200, difficulty: 'legendary', description: 'Comer bem e se exercitar.', is_system: true },

    // --- 🎨 HABILIDADES & OFFLINE (151-175) ---
    { id: 'sys_151', title: 'Dia Sem Telas', icon: 'cellphone-off', reward: 500, difficulty: 'legendary', description: '24h sem eletrônicos.', is_system: true, use_critical: true, critical_type: 'bonus_coins', critical_chance: 50 },
    { id: 'sys_152', title: 'Ler um Livro (30min)', icon: 'book-open-variant', reward: 100, difficulty: 'rare', description: 'Leitura focada.', is_system: true },
    { id: 'sys_153', title: 'Desenhar ou Pintar', icon: 'palette', reward: 60, difficulty: 'rare', description: 'Atividade artística.', is_system: true },
    { id: 'sys_154', title: 'Montar Quebra-Cabeça', icon: 'puzzle', reward: 80, difficulty: 'rare', description: 'Exercício mental.', is_system: true },
    { id: 'sys_155', title: 'Brincar de LEGO', icon: 'toy-brick', reward: 50, difficulty: 'common', description: 'Construir algo novo.', is_system: true },
    { id: 'sys_156', title: 'Tocar Instrumento', icon: 'guitar-acoustic', reward: 100, difficulty: 'rare', description: 'Praticar música.', is_system: true },
    { id: 'sys_157', title: 'Andar de Bicicleta', icon: 'bike', reward: 80, difficulty: 'rare', description: 'Exercício ao ar livre.', is_system: true },
    { id: 'sys_158', title: 'Pular Corda', icon: 'jump-rope', reward: 40, difficulty: 'common', description: 'Gastar energia.', is_system: true },
    { id: 'sys_159', title: 'Jogar Bola', icon: 'soccer', reward: 50, difficulty: 'common', description: 'Futebol ou vôlei.', is_system: true },
    { id: 'sys_160', title: 'Escrever uma História', icon: 'pencil', reward: 120, difficulty: 'epic', description: 'Criar um conto.', is_system: true },
    { id: 'sys_161', title: 'Fazer Origami', icon: 'paper-cut-vertical', reward: 60, difficulty: 'rare', description: 'Arte com papel.', is_system: true },
    { id: 'sys_162', title: 'Dançar', icon: 'music-note', reward: 30, difficulty: 'common', description: 'Se mexer com música.', is_system: true },
    { id: 'sys_163', title: 'Aprender Algo Novo', icon: 'lightbulb-on', reward: 150, difficulty: 'epic', description: 'Uma curiosidade ou habilidade.', is_system: true },
    { id: 'sys_164', title: 'Jogar Jogo de Tabuleiro', icon: 'dice-5', reward: 70, difficulty: 'rare', description: 'Em família ou com amigos.', is_system: true },
    { id: 'sys_165', title: 'Fazer Mágica', icon: 'magic-staff', reward: 60, difficulty: 'rare', description: 'Aprender um truque.', is_system: true },
    { id: 'sys_166', title: 'Cuidar da Horta', icon: 'sprout', reward: 80, difficulty: 'rare', description: 'Mexer na terra.', is_system: true },
    { id: 'sys_167', title: 'Acampar no Quintal/Sala', icon: 'tent', reward: 200, difficulty: 'legendary', description: 'Aventura em casa.', is_system: true },
    { id: 'sys_168', title: 'Fazer Experiência', icon: 'flask-empty', reward: 100, difficulty: 'rare', description: 'Ciência divertida.', is_system: true },
    { id: 'sys_169', title: 'Costurar (com ajuda)', icon: 'needle', reward: 120, difficulty: 'epic', description: 'Pregar botão ou consertar.', is_system: true },
    { id: 'sys_170', title: 'Tomar remédio', icon: 'pill', reward: 30, difficulty: 'common', description: 'Tomar o medicamento na hora certa.', is_system: true },
    { id: 'sys_171', title: 'Meditar 5 min', icon: 'yoga', reward: 60, difficulty: 'rare', description: 'Ficar em silêncio.', is_system: true },
    { id: 'sys_172', title: 'Fazer Alongamento', icon: 'human-handsup', reward: 40, difficulty: 'common', description: 'Esticar o corpo.', is_system: true },
    { id: 'sys_173', title: 'Treinar Embaixadinha', icon: 'soccer', reward: 50, difficulty: 'rare', description: 'Controle de bola.', is_system: true },
    { id: 'sys_174', title: 'Aprender Nó', icon: 'vector-curve', reward: 60, difficulty: 'rare', description: 'Fazer nó de escoteiro.', is_system: true },
    { id: 'sys_175', title: 'Resolver Cubo Mágico', icon: 'cube-outline', reward: 300, difficulty: 'legendary', description: 'Desafio de lógica.', is_system: true },

    // --- 🧹 LIMPEZA PESADA & JARDIM (176-190) ---
    { id: 'sys_176', title: 'Lavar o Carro', icon: 'car-wash', reward: 250, difficulty: 'legendary', description: 'Lavar por fora.', is_system: true, use_critical: true, critical_type: 'custom_item', critical_custom_reward: 'Sorvete', critical_chance: 30 },
    { id: 'sys_177', title: 'Aspirar o Carro', icon: 'car-seat', reward: 150, difficulty: 'epic', description: 'Limpar por dentro.', is_system: true },
    { id: 'sys_178', title: 'Cortar a Grama', icon: 'grass', reward: 200, difficulty: 'epic', description: 'Cuidar do jardim.', is_system: true },
    { id: 'sys_179', title: 'Varrer Calçada', icon: 'broom', reward: 80, difficulty: 'rare', description: 'Limpar a frente de casa.', is_system: true },
    { id: 'sys_180', title: 'Limpar Piscina', icon: 'pool', reward: 150, difficulty: 'epic', description: 'Peneirar folhas.', is_system: true },
    { id: 'sys_181', title: 'Limpar Vidros', icon: 'window-closed', reward: 120, difficulty: 'epic', description: 'Limpar janelas baixas.', is_system: true },
    { id: 'sys_182', title: 'Limpar Ventilador', icon: 'fan', reward: 100, difficulty: 'epic', description: 'Tirar poeira das pás.', is_system: true },
    { id: 'sys_183', title: 'Limpar Geladeira', icon: 'fridge-outline', reward: 200, difficulty: 'legendary', description: 'Faxina interna.', is_system: true },
    { id: 'sys_184', title: 'Organizar Garagem', icon: 'garage', reward: 150, difficulty: 'epic', description: 'Arrumar bagunça.', is_system: true },
    { id: 'sys_185', title: 'Limpar Rodapés', icon: 'brush', reward: 100, difficulty: 'epic', description: 'Passar pano nos cantinhos.', is_system: true },
    { id: 'sys_186', title: 'Lavar Tênis', icon: 'shoe-sneaker', reward: 120, difficulty: 'epic', description: 'Lavar e colocar pra secar.', is_system: true },
    { id: 'sys_187', title: 'Limpar Bicicleta', icon: 'bike', reward: 80, difficulty: 'rare', description: 'Deixar brilhando.', is_system: true },
    { id: 'sys_188', title: 'Recolher Folhas', icon: 'leaf', reward: 70, difficulty: 'rare', description: 'Juntar folhas secas.', is_system: true },
    { id: 'sys_189', title: 'Limpar Maçanetas', icon: 'door', reward: 50, difficulty: 'common', description: 'Passar álcool nas portas.', is_system: true },
    { id: 'sys_190', title: 'Tirar Lixo Reciclável', icon: 'recycle', reward: 40, difficulty: 'common', description: 'Separar e levar fora.', is_system: true },

    // --- 🌟 EXTRAS & ESPECIAIS (191-200) ---
    { id: 'sys_191', title: 'Economizar Mesada', icon: 'piggy-bank', reward: 50, difficulty: 'rare', description: 'Guardar moedinhas.', is_system: true },
    { id: 'sys_192', title: 'Arrumar Mala de Viagem', icon: 'bag-suitcase', reward: 100, difficulty: 'rare', description: 'Preparar roupas para viajar.', is_system: true },
    { id: 'sys_193', title: 'Saber Endereço', icon: 'map-marker', reward: 100, difficulty: 'epic', description: 'Decorar endereço de casa.', is_system: true },
    { id: 'sys_194', title: 'Saber Telefone dos Pais', icon: 'phone-classic', reward: 100, difficulty: 'epic', description: 'Decorar número de emergência.', is_system: true },
    { id: 'sys_195', title: 'Missão Secreta', icon: 'incognito', reward: 500, difficulty: 'legendary', description: 'Faça algo incrível surpresa!', is_system: true, use_critical: true, critical_type: 'custom_item', critical_custom_reward: 'Cinema', critical_chance: 20 },
    { id: 'sys_196', title: 'Ajudar nas Compras', icon: 'cart', reward: 80, difficulty: 'rare', description: 'Ir ao mercado e ajudar.', is_system: true },
    { id: 'sys_197', title: 'Fazer Lista de Compras', icon: 'format-list-checks', reward: 40, difficulty: 'common', description: 'Anotar o que falta.', is_system: true },
    { id: 'sys_198', title: 'Doar Roupas', icon: 'hanger', reward: 200, difficulty: 'legendary', description: 'Separar o que não serve mais.', is_system: true },
    { id: 'sys_199', title: 'Limpar a Tela do Celular', icon: 'cellphone', reward: 20, difficulty: 'common', description: 'Tirar marcas de dedo.', is_system: true },
    { id: 'sys_200', title: 'Dar um Abraço', icon: 'human-greeting', reward: 1000, difficulty: 'legendary', description: 'Abraço bem apertado nos pais!', is_system: true, use_critical: true, critical_type: 'bonus_coins', critical_chance: 100 }
];